#!/bin/bash
sudo systemctl stop systemd-resolved
sudo bash -c 'echo "nameserver 8.8.8.8" > /etc/resolv.conf'
sudo bash -c 'echo "nameserver 8.8.4.4" >> /etc/resolv.conf'
echo "
       Проверка
"
cat /etc/resolv.conf
